# Generated by Django 3.2.7 on 2021-09-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_description'),
        ('category', '0002_alter_category_options'),
    ]

    operations = [
    ]
