# Generated by Django 3.2.7 on 2021-10-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
